// Registro de times/seleções (nome, escudo, escopo) usado pelo filtro do catálogo.
// Gerado por build_products_js.py a partir de teams_registry.py.
window.DA_TEAMS = [
  { slug: 'selecao-brasileira', name: 'Seleção Brasileira', scope: 'selecao', logo: 'src/img/teams/selecoes/selecao-brasileira.jpg', count: 78 },
  { slug: 'argentina', name: 'Argentina', scope: 'selecao', logo: 'src/img/teams/selecoes/argentina.jpg', count: 38 },
  { slug: 'espanha', name: 'Espanha', scope: 'selecao', logo: 'src/img/teams/selecoes/espanha.jpg', count: 19 },
  { slug: 'franca', name: 'França', scope: 'selecao', logo: 'src/img/teams/selecoes/franca.jpg', count: 23 },
  { slug: 'inglaterra', name: 'Inglaterra', scope: 'selecao', logo: 'src/img/teams/selecoes/inglaterra.jpg', count: 25 },
  { slug: 'alemanha', name: 'Alemanha', scope: 'selecao', logo: 'src/img/teams/selecoes/alemanha.jpg', count: 26 },
  { slug: 'portugal', name: 'Portugal', scope: 'selecao', logo: 'src/img/teams/internacionais/portugal.jpg', count: 32 },
  { slug: 'estados-unidos', name: 'Estados Unidos', scope: 'selecao', logo: 'src/img/teams/selecoes/estados-unidos.jpg', count: 4 },
  { slug: 'japao', name: 'Japão', scope: 'selecao', logo: 'src/img/teams/selecoes/japao.jpg', count: 32 },
  { slug: 'colombia', name: 'Colômbia', scope: 'selecao', logo: 'src/img/teams/internacionais/colombia.png', count: 9 },
  { slug: 'inter-miami', name: 'Inter Miami', scope: 'internacional', logo: 'src/img/teams/internacionais/inter-miami.png', count: 25 },
  { slug: 'inter-de-milao', name: 'Inter de Milão', scope: 'internacional', logo: 'src/img/teams/internacionais/inter-de-milao.png', count: 37 },
  { slug: 'milan', name: 'Milan', scope: 'internacional', logo: 'src/img/teams/internacionais/milan.webp', count: 55 },
  { slug: 'real-madrid', name: 'Real Madrid', scope: 'internacional', logo: 'src/img/teams/internacionais/real-madrid.webp', count: 123 },
  { slug: 'atletico-de-madrid', name: 'Atlético de Madrid', scope: 'internacional', logo: 'src/img/teams/internacionais/atletico-de-madrid.png', count: 24 },
  { slug: 'barcelona', name: 'Barcelona', scope: 'internacional', logo: 'src/img/teams/internacionais/barcelona.webp', count: 99 },
  { slug: 'celta-de-vigo', name: 'Celta de Vigo', scope: 'internacional', logo: 'src/img/teams/internacionais/celta-de-vigo.png', count: 1 },
  { slug: 'manchester-united', name: 'Manchester United', scope: 'internacional', logo: 'src/img/teams/internacionais/manchester-united.webp', count: 79 },
  { slug: 'manchester-city', name: 'Manchester City', scope: 'internacional', logo: 'src/img/teams/internacionais/manchester-city.webp', count: 58 },
  { slug: 'liverpool', name: 'Liverpool', scope: 'internacional', logo: 'src/img/teams/internacionais/liverpool.webp', count: 64 },
  { slug: 'chelsea', name: 'Chelsea', scope: 'internacional', logo: 'src/img/teams/internacionais/chelsea.webp', count: 50 },
  { slug: 'arsenal', name: 'Arsenal', scope: 'internacional', logo: 'src/img/teams/internacionais/arsenal.webp', count: 68 },
  { slug: 'aston-villa', name: 'Aston Villa', scope: 'internacional', logo: 'src/img/teams/internacionais/aston-villa.png', count: 6 },
  { slug: 'everton', name: 'Everton', scope: 'internacional', logo: 'src/img/teams/internacionais/everton.png', count: 2 },
  { slug: 'leeds-united', name: 'Leeds United', scope: 'internacional', logo: 'src/img/teams/internacionais/leeds-united.png', count: 5 },
  { slug: 'leicester-city', name: 'Leicester City', scope: 'internacional', logo: 'src/img/teams/internacionais/leicester-city.png', count: 1 },
  { slug: 'newcastle-united', name: 'Newcastle United', scope: 'internacional', logo: 'src/img/teams/internacionais/newcastle-united.png', count: 24 },
  { slug: 'norwich-city', name: 'Norwich City', scope: 'internacional', logo: 'src/img/teams/internacionais/norwich-city.png', count: 0 },
  { slug: 'hull-city', name: 'Hull City', scope: 'internacional', logo: 'src/img/teams/internacionais/hull-city.png', count: 0 },
  { slug: 'bayern-de-munique', name: 'Bayern de Munique', scope: 'internacional', logo: 'src/img/teams/internacionais/bayern-de-munique.webp', count: 39 },
  { slug: 'borussia-dortmund', name: 'Borussia Dortmund', scope: 'internacional', logo: 'src/img/teams/internacionais/borussia-dortmund.webp', count: 22 },
  { slug: 'rb-leipzig', name: 'RB Leipzig', scope: 'internacional', logo: 'src/img/teams/internacionais/rb-leipzig.png', count: 1 },
  { slug: 'frankfurt', name: 'Eintracht Frankfurt', scope: 'internacional', logo: 'src/img/teams/internacionais/frankfurt.png', count: 2 },
  { slug: 'juventus', name: 'Juventus', scope: 'internacional', logo: 'src/img/teams/internacionais/juventus.webp', count: 41 },
  { slug: 'napoli', name: 'Napoli', scope: 'internacional', logo: 'src/img/teams/internacionais/napoli.png', count: 28 },
  { slug: 'lazio', name: 'Lazio', scope: 'internacional', logo: 'src/img/teams/internacionais/lazio.png', count: 4 },
  { slug: 'paris-saint-germain', name: 'Paris Saint-Germain', scope: 'internacional', logo: 'src/img/teams/internacionais/paris-saint-germain.webp', count: 69 },
  { slug: 'olympique-de-marseille', name: 'Olympique de Marselha', scope: 'internacional', logo: 'src/img/teams/internacionais/olympique-de-marseille.png', count: 7 },
  { slug: 'lyon', name: 'Lyon', scope: 'internacional', logo: 'src/img/teams/internacionais/lyon.png', count: 8 },
  { slug: 'porto', name: 'Porto', scope: 'internacional', logo: 'src/img/teams/internacionais/porto.png', count: 10 },
  { slug: 'benfica', name: 'Benfica', scope: 'internacional', logo: 'src/img/teams/internacionais/benfica.png', count: 16 },
  { slug: 'al-hilal', name: 'Al-Hilal', scope: 'internacional', logo: 'src/img/teams/internacionais/al-hilal.png', count: 13 },
  { slug: 'al-nassr', name: 'Al-Nassr', scope: 'internacional', logo: 'src/img/teams/internacionais/al-nassr.png', count: 13 },
  { slug: 'al-ittihad', name: 'Al-Ittihad', scope: 'internacional', logo: 'src/img/teams/internacionais/al-ittihad.png', count: 1 },
  { slug: 'la-galaxy', name: 'LA Galaxy', scope: 'internacional', logo: 'src/img/teams/internacionais/la-galaxy.png', count: 1 },
  { slug: 'los-angeles-fc', name: 'Los Angeles FC', scope: 'internacional', logo: 'src/img/teams/internacionais/los-angeles-fc.png', count: 3 },
  { slug: 'new-york-city', name: 'New York City FC', scope: 'internacional', logo: 'src/img/teams/internacionais/new-york-city.png', count: 1 },
  { slug: 'orlando-city', name: 'Orlando City', scope: 'internacional', logo: 'src/img/teams/internacionais/orlando-city.png', count: 1 },
  { slug: 'flamengo', name: 'Flamengo', scope: 'nacional', logo: 'src/img/teams/brasileiros/flamengo.webp', count: 89 },
  { slug: 'corinthians', name: 'Corinthians', scope: 'nacional', logo: 'src/img/teams/brasileiros/corinthians.webp', count: 64 },
  { slug: 'palmeiras', name: 'Palmeiras', scope: 'nacional', logo: 'src/img/teams/brasileiros/palmeiras.webp', count: 66 },
  { slug: 'sao-paulo', name: 'São Paulo', scope: 'nacional', logo: 'src/img/teams/brasileiros/sao-paulo.webp', count: 52 },
  { slug: 'santos', name: 'Santos', scope: 'nacional', logo: 'src/img/teams/brasileiros/santos.webp', count: 1 },
  { slug: 'vasco', name: 'Vasco da Gama', scope: 'nacional', logo: 'src/img/teams/brasileiros/vasco.webp', count: 53 },
  { slug: 'botafogo', name: 'Botafogo', scope: 'nacional', logo: 'src/img/teams/brasileiros/botafogo.webp', count: 42 },
  { slug: 'fluminense', name: 'Fluminense', scope: 'nacional', logo: 'src/img/teams/brasileiros/fluminense.webp', count: 27 },
  { slug: 'atletico-mineiro', name: 'Atlético Mineiro', scope: 'nacional', logo: 'src/img/teams/brasileiros/atletico-mineiro.webp', count: 24 },
  { slug: 'cruzeiro', name: 'Cruzeiro', scope: 'nacional', logo: 'src/img/teams/brasileiros/cruzeiro.webp', count: 40 },
  { slug: 'gremio', name: 'Grêmio', scope: 'nacional', logo: 'src/img/teams/brasileiros/gremio.png', count: 25 },
  { slug: 'bahia', name: 'Bahia', scope: 'nacional', logo: 'src/img/teams/brasileiros/bahia.png', count: 17 },
  { slug: 'fortaleza', name: 'Fortaleza', scope: 'nacional', logo: 'src/img/teams/brasileiros/fortaleza.png', count: 4 },
  { slug: 'internacional-clube', name: 'Internacional', scope: 'nacional', logo: 'src/img/teams/brasileiros/internacional.webp', count: 86 },
];
