# Registro de times/seleções usado pelo build_products_js.py para identificar
# o time de cada produto (a partir do título) e gerar o filtro por time no site.
# scope: 'nacional' (clubes brasileiros) | 'internacional' (clubes estrangeiros) | 'selecao'
#
# Cada entrada: slug, name (nome de exibição), scope, logo (caminho relativo dentro de
# src/img/teams/), aliases (lista de variações de texto a procurar no título/tags do produto,
# já sem acento e em minúsculo — a checagem normaliza título e alias do mesmo jeito).
# A ordem da lista importa: nomes mais específicos (ex.: "inter miami", "inter de milao")
# vêm antes de nomes genéricos que poderiam dar falso positivo (ex.: "internacional").

TEAMS = [
    # ---- selecoes ----
    {'slug': 'selecao-brasileira', 'name': 'Seleção Brasileira', 'scope': 'selecao', 'logo': 'selecoes/selecao-brasileira.jpg',
     'aliases': ['selecao brasileira', 'selecao brasil', 'brasil']},
    {'slug': 'argentina', 'name': 'Argentina', 'scope': 'selecao', 'logo': 'selecoes/argentina.jpg',
     'aliases': ['selecao argentina', 'argentina']},
    {'slug': 'espanha', 'name': 'Espanha', 'scope': 'selecao', 'logo': 'selecoes/espanha.jpg',
     'aliases': ['selecao espanha', 'espanha']},
    {'slug': 'franca', 'name': 'França', 'scope': 'selecao', 'logo': 'selecoes/franca.jpg',
     'aliases': ['selecao franca', 'franca']},
    {'slug': 'inglaterra', 'name': 'Inglaterra', 'scope': 'selecao', 'logo': 'selecoes/inglaterra.jpg',
     'aliases': ['selecao inglaterra', 'inglaterra']},
    {'slug': 'alemanha', 'name': 'Alemanha', 'scope': 'selecao', 'logo': 'selecoes/alemanha.jpg',
     'aliases': ['selecao alemanha', 'alemanha']},
    {'slug': 'portugal', 'name': 'Portugal', 'scope': 'selecao', 'logo': 'internacionais/portugal.jpg',
     'aliases': ['selecao portugal', 'portugal']},
    {'slug': 'estados-unidos', 'name': 'Estados Unidos', 'scope': 'selecao', 'logo': 'selecoes/estados-unidos.jpg',
     'aliases': ['selecao estados unidos', 'estados unidos', 'eua']},
    {'slug': 'japao', 'name': 'Japão', 'scope': 'selecao', 'logo': 'selecoes/japao.jpg',
     'aliases': ['selecao japao', 'japao']},
    {'slug': 'colombia', 'name': 'Colômbia', 'scope': 'selecao', 'logo': 'internacionais/colombia.png',
     'aliases': ['selecao colombia', 'colombia']},

    # ---- internacionais (clubes específicos antes dos genéricos) ----
    {'slug': 'inter-miami', 'name': 'Inter Miami', 'scope': 'internacional', 'logo': 'internacionais/inter-miami.png',
     'aliases': ['inter miami']},
    {'slug': 'inter-de-milao', 'name': 'Inter de Milão', 'scope': 'internacional', 'logo': 'internacionais/inter-de-milao.png',
     'aliases': ['inter de milao', 'inter milan', 'internazionale']},
    {'slug': 'milan', 'name': 'Milan', 'scope': 'internacional', 'logo': 'internacionais/milan.webp',
     'aliases': ['ac milan', 'a.c. milan', 'milan']},
    {'slug': 'real-madrid', 'name': 'Real Madrid', 'scope': 'internacional', 'logo': 'internacionais/real-madrid.webp',
     'aliases': ['real madrid']},
    {'slug': 'atletico-de-madrid', 'name': 'Atlético de Madrid', 'scope': 'internacional', 'logo': 'internacionais/atletico-de-madrid.png',
     'aliases': ['atletico de madrid', 'atletico madrid']},
    {'slug': 'barcelona', 'name': 'Barcelona', 'scope': 'internacional', 'logo': 'internacionais/barcelona.webp',
     'aliases': ['barcelona']},
    {'slug': 'celta-de-vigo', 'name': 'Celta de Vigo', 'scope': 'internacional', 'logo': 'internacionais/celta-de-vigo.png',
     'aliases': ['celta de vigo', 'celta vigo']},
    {'slug': 'manchester-united', 'name': 'Manchester United', 'scope': 'internacional', 'logo': 'internacionais/manchester-united.webp',
     'aliases': ['manchester united']},
    {'slug': 'manchester-city', 'name': 'Manchester City', 'scope': 'internacional', 'logo': 'internacionais/manchester-city.webp',
     'aliases': ['manchester city']},
    {'slug': 'liverpool', 'name': 'Liverpool', 'scope': 'internacional', 'logo': 'internacionais/liverpool.webp',
     'aliases': ['liverpool']},
    {'slug': 'chelsea', 'name': 'Chelsea', 'scope': 'internacional', 'logo': 'internacionais/chelsea.webp',
     'aliases': ['chelsea']},
    {'slug': 'arsenal', 'name': 'Arsenal', 'scope': 'internacional', 'logo': 'internacionais/arsenal.webp',
     'aliases': ['arsenal']},
    {'slug': 'aston-villa', 'name': 'Aston Villa', 'scope': 'internacional', 'logo': 'internacionais/aston-villa.png',
     'aliases': ['aston villa']},
    {'slug': 'everton', 'name': 'Everton', 'scope': 'internacional', 'logo': 'internacionais/everton.png',
     'aliases': ['everton']},
    {'slug': 'leeds-united', 'name': 'Leeds United', 'scope': 'internacional', 'logo': 'internacionais/leeds-united.png',
     'aliases': ['leeds united', 'leeds']},
    {'slug': 'leicester-city', 'name': 'Leicester City', 'scope': 'internacional', 'logo': 'internacionais/leicester-city.png',
     'aliases': ['leicester city', 'leicester']},
    {'slug': 'newcastle-united', 'name': 'Newcastle United', 'scope': 'internacional', 'logo': 'internacionais/newcastle-united.png',
     'aliases': ['newcastle united', 'newcastle']},
    {'slug': 'norwich-city', 'name': 'Norwich City', 'scope': 'internacional', 'logo': 'internacionais/norwich-city.png',
     'aliases': ['norwich city', 'norwich']},
    {'slug': 'hull-city', 'name': 'Hull City', 'scope': 'internacional', 'logo': 'internacionais/hull-city.png',
     'aliases': ['hull city']},
    {'slug': 'bayern-de-munique', 'name': 'Bayern de Munique', 'scope': 'internacional', 'logo': 'internacionais/bayern-de-munique.webp',
     'aliases': ['bayern de munique', 'bayern munique', 'bayern munich', 'bayern de munchen']},
    {'slug': 'borussia-dortmund', 'name': 'Borussia Dortmund', 'scope': 'internacional', 'logo': 'internacionais/borussia-dortmund.webp',
     'aliases': ['borussia dortmund', 'dortmund']},
    {'slug': 'rb-leipzig', 'name': 'RB Leipzig', 'scope': 'internacional', 'logo': 'internacionais/rb-leipzig.png',
     'aliases': ['rb leipzig', 'leipzig']},
    {'slug': 'frankfurt', 'name': 'Eintracht Frankfurt', 'scope': 'internacional', 'logo': 'internacionais/frankfurt.png',
     'aliases': ['eintracht frankfurt', 'frankfurt']},
    {'slug': 'juventus', 'name': 'Juventus', 'scope': 'internacional', 'logo': 'internacionais/juventus.webp',
     'aliases': ['juventus']},
    {'slug': 'napoli', 'name': 'Napoli', 'scope': 'internacional', 'logo': 'internacionais/napoli.png',
     'aliases': ['napoli']},
    {'slug': 'lazio', 'name': 'Lazio', 'scope': 'internacional', 'logo': 'internacionais/lazio.png',
     'aliases': ['lazio']},
    {'slug': 'paris-saint-germain', 'name': 'Paris Saint-Germain', 'scope': 'internacional', 'logo': 'internacionais/paris-saint-germain.webp',
     'aliases': ['paris saint germain', 'psg']},
    {'slug': 'olympique-de-marseille', 'name': 'Olympique de Marselha', 'scope': 'internacional', 'logo': 'internacionais/olympique-de-marseille.png',
     'aliases': ['olympique de marseille', 'olympique marseille', 'marselha']},
    {'slug': 'lyon', 'name': 'Lyon', 'scope': 'internacional', 'logo': 'internacionais/lyon.png',
     'aliases': ['olympique lyonnais', 'lyon']},
    {'slug': 'porto', 'name': 'Porto', 'scope': 'internacional', 'logo': 'internacionais/porto.png',
     'aliases': ['fc porto', 'porto']},
    {'slug': 'benfica', 'name': 'Benfica', 'scope': 'internacional', 'logo': 'internacionais/benfica.png',
     'aliases': ['benfica']},
    {'slug': 'al-hilal', 'name': 'Al-Hilal', 'scope': 'internacional', 'logo': 'internacionais/al-hilal.png',
     'aliases': ['al hilal', 'al-hilal']},
    {'slug': 'al-nassr', 'name': 'Al-Nassr', 'scope': 'internacional', 'logo': 'internacionais/al-nassr.png',
     'aliases': ['al nassr', 'al-nassr']},
    {'slug': 'al-ittihad', 'name': 'Al-Ittihad', 'scope': 'internacional', 'logo': 'internacionais/al-ittihad.png',
     'aliases': ['al ittihad', 'al-ittihad']},
    {'slug': 'la-galaxy', 'name': 'LA Galaxy', 'scope': 'internacional', 'logo': 'internacionais/la-galaxy.png',
     'aliases': ['la galaxy', 'los angeles galaxy']},
    {'slug': 'los-angeles-fc', 'name': 'Los Angeles FC', 'scope': 'internacional', 'logo': 'internacionais/los-angeles-fc.png',
     'aliases': ['los angeles fc', 'lafc']},
    {'slug': 'new-york-city', 'name': 'New York City FC', 'scope': 'internacional', 'logo': 'internacionais/new-york-city.png',
     'aliases': ['new york city']},
    {'slug': 'orlando-city', 'name': 'Orlando City', 'scope': 'internacional', 'logo': 'internacionais/orlando-city.png',
     'aliases': ['orlando city']},

    # ---- brasileiros (nacional) — "internacional" (clube) checado por último, depois dos outros ----
    {'slug': 'flamengo', 'name': 'Flamengo', 'scope': 'nacional', 'logo': 'brasileiros/flamengo.webp',
     'aliases': ['flamengo']},
    {'slug': 'corinthians', 'name': 'Corinthians', 'scope': 'nacional', 'logo': 'brasileiros/corinthians.webp',
     'aliases': ['corinthians']},
    {'slug': 'palmeiras', 'name': 'Palmeiras', 'scope': 'nacional', 'logo': 'brasileiros/palmeiras.webp',
     'aliases': ['palmeiras']},
    {'slug': 'sao-paulo', 'name': 'São Paulo', 'scope': 'nacional', 'logo': 'brasileiros/sao-paulo.webp',
     'aliases': ['sao paulo']},
    {'slug': 'santos', 'name': 'Santos', 'scope': 'nacional', 'logo': 'brasileiros/santos.webp',
     'aliases': ['santos']},
    {'slug': 'vasco', 'name': 'Vasco da Gama', 'scope': 'nacional', 'logo': 'brasileiros/vasco.webp',
     'aliases': ['vasco da gama', 'vasco']},
    {'slug': 'botafogo', 'name': 'Botafogo', 'scope': 'nacional', 'logo': 'brasileiros/botafogo.webp',
     'aliases': ['botafogo']},
    {'slug': 'fluminense', 'name': 'Fluminense', 'scope': 'nacional', 'logo': 'brasileiros/fluminense.webp',
     'aliases': ['fluminense']},
    {'slug': 'atletico-mineiro', 'name': 'Atlético Mineiro', 'scope': 'nacional', 'logo': 'brasileiros/atletico-mineiro.webp',
     'aliases': ['atletico mineiro', 'atletico-mg']},
    {'slug': 'cruzeiro', 'name': 'Cruzeiro', 'scope': 'nacional', 'logo': 'brasileiros/cruzeiro.webp',
     'aliases': ['cruzeiro']},
    {'slug': 'gremio', 'name': 'Grêmio', 'scope': 'nacional', 'logo': 'brasileiros/gremio.png',
     'aliases': ['gremio']},
    {'slug': 'bahia', 'name': 'Bahia', 'scope': 'nacional', 'logo': 'brasileiros/bahia.png',
     'aliases': ['bahia']},
    {'slug': 'fortaleza', 'name': 'Fortaleza', 'scope': 'nacional', 'logo': 'brasileiros/fortaleza.png',
     'aliases': ['fortaleza']},
    {'slug': 'internacional-clube', 'name': 'Internacional', 'scope': 'nacional', 'logo': 'brasileiros/internacional.webp',
     'aliases': ['sc internacional', 'internacional']},
]
